#!/usr/bin/env python3
"""Build the pre-market briefing markdown.

Reports what happened — prior-day moves, sector ranks, overnight headlines
with the publisher visible — and tags each headline by corroboration:
a story matched across two or more independent publisher domains is
"corroborated"; a story from one outlet is labeled unconfirmed. No claim
here is a recommendation; the briefing links sources and stops there.

Usage: python3 scripts/morning_briefing.py [output.md]
"""

import json
import re
import sys
from datetime import datetime, timezone
from urllib.parse import urlparse

sys.path.insert(0, "scripts")
from update_news import fetch_headlines  # noqa: E402

STOPWORDS = frozenset(
    "a an the and or but of to in on for with as at by is are was were be "
    "this that these those its it his her their after before over under "
    "here why how what stock stocks share shares says said say".split()
)
MIN_SHARED_TOKENS = 3


def tokens(title: str) -> set:
    words = re.findall(r"[a-z0-9]+", title.lower())
    return {w for w in words if len(w) > 2 and w not in STOPWORDS}


def domain(link: str) -> str:
    try:
        return urlparse(link).hostname.removeprefix("www.")
    except Exception:
        return ""


def tag_corroboration(items: list[dict]) -> None:
    """Annotate each headline with how many distinct domains echo its story."""
    for item in items:
        item_toks = tokens(item["title"])
        outlets = {domain(item["link"])}
        for other in items:
            if other is item:
                continue
            if domain(other["link"]) in outlets:
                continue
            if len(item_toks & tokens(other["title"])) >= MIN_SHARED_TOKENS:
                outlets.add(domain(other["link"]))
        item["outlets"] = len(outlets)


def arrow(pct: float) -> str:
    return "▲" if pct > 0 else ("▼" if pct < 0 else "•")


def build_briefing(quotes_data: dict, news: dict) -> str:
    now = datetime.now(timezone.utc)
    lines = [
        f"## Pre-market briefing — {now:%A, %B %d, %Y}",
        "",
        "_Data display with primary sources — not investment advice. "
        "Headlines marked **corroborated** appear in 2+ independent outlets; "
        "**single source** stories are unconfirmed._",
        "",
        f"Prices as of last close ({quotes_data['updated']}).",
        "",
        "### Prior close",
        "",
        "| Symbol | Close | 1 Day | |",
        "|---|---|---|---|",
    ]
    core_flagged = [q for q in quotes_data.get("core", []) if q.get("significant")]
    for q in quotes_data["quotes"] + core_flagged:
        flag = "⚠ ±3% move" if q.get("significant") else ""
        lines.append(
            f"| {q['symbol']} | ${q['close']:.2f} | "
            f"{arrow(q['d1'])} {q['d1']:+.2f}% | {flag} |"
        )

    sectors = sorted(
        quotes_data.get("sectors", []), key=lambda s: s["d1"], reverse=True
    )
    if sectors:
        lines += ["", "### Sector pulse (prior day)", ""]
        for label, group in (("Leaders", sectors[:3]), ("Laggards", sectors[-3:])):
            entries = ", ".join(
                f"{s['name']} {arrow(s['d1'])} {s['d1']:+.2f}%" for s in group
            )
            lines.append(f"- **{label}:** {entries}")

    lines += ["", "### Overnight headlines", ""]
    if not news:
        lines.append("_Headline fetch failed this run — see the tracker page's news panel later._")
    for symbol, items in news.items():
        tag_corroboration(items)
        lines.append(f"**{symbol}**")
        for item in items:
            tag = (
                f"corroborated ({item['outlets']} outlets)"
                if item["outlets"] >= 2
                else "single source — unconfirmed"
            )
            lines.append(
                f"- [{item['title']}]({item['link']}) — "
                f"{domain(item['link'])} · _{tag}_"
            )
        lines.append("")

    lines.append(
        "---\n_Generated by the scheduled briefing workflow. "
        "Tracker: https://modernuser.github.io/skills-introduction-to-github/tracker.html_"
    )
    return "\n".join(lines)


def main() -> int:
    out_path = sys.argv[1] if len(sys.argv) > 1 else "briefing.md"
    with open("data/quotes.json") as f:
        quotes_data = json.load(f)

    news = {}
    for q in quotes_data["quotes"]:
        try:
            items = fetch_headlines(q["symbol"])
            if items:
                news[q["symbol"]] = items
        except Exception as exc:
            print(f"news fetch failed for {q['symbol']}: {exc}", file=sys.stderr)

    with open(out_path, "w") as f:
        f.write(build_briefing(quotes_data, news))
    print(f"Wrote {out_path}: {len(quotes_data['quotes'])} symbols, "
          f"{len(news)} with headlines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
